#!/usr/bin/env node
// fixtures/fake-worker.mjs — a deterministic stand-in for a coding-worker CLI used by e2e tests.
// Reads the self-contained task from .ultraswarm-prompt.txt (written by the runner into the
// per-task worktree), parses its `Files to modify: [...]` line, and writes each listed file with
// stub content. Writing the task's OWN distinct files (rather than a single hardcoded path) lets
// a multi-task plan integrate without cross-branch merge conflicts. Prints a token line so the
// adapter's usage parser has something to read.
import fs from 'node:fs'
import path from 'node:path'

let files = []
try {
  const prompt = fs.readFileSync('.ultraswarm-prompt.txt', 'utf8')
  const m = prompt.match(/Files to modify:\s*(\[[^\]]*\])/)
  if (m) files = JSON.parse(m[1])
} catch {}

// Fallback so the worker always produces a change even if the prompt lacks a files list.
if (!Array.isArray(files) || files.length === 0) files = ['generated.js']

for (const f of files) {
  const dir = path.dirname(f)
  if (dir && dir !== '.') fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(f, `// generated by fake-worker for ${f}\nexport const ok = true\n`)
}

console.log(`tokens used: ${1000 + files.length}`)
